name: Aparajitha
favicon: null
layout_spectrum: 0.729859790764749
typography_spectrum: 0.77869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#311d3f'
    - '#88304e'
    - '#e23e57'
    - '#ffffff'
    - '#979b9d'
  brandStrength: 0.9983208503108472
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.4566677794791758
purpose: []
